run:
  timeout: 5m
  tests: true

linters:
  enable:
    - bodyclose
    - errorlint
    - exhaustive
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  sort-results: true

